nome = input('digite o nome da aluna: ')
idade = int(input('digite a idade da aluna: '))
altura = float(input('digite a altura da aluna: '))
hobbies = input('digite os hobbies da aluna separados por virgula:')
hobbies = hobbies.split(',')
endereço_rua = input('digite o endereço da aluna: ')
endereço_numero = int(input('digite o numero da aluna: '))
endereço_cidade = input('digite a cidade da aluna: ')
endereço = (endereço_rua, endereço_numero, endereço_cidade)
email = input('digite o email da aluna: ')
telefone = input('digite o telefone da aluna: ')
contato ={'email': email, 'telefone': telefone}
print ('\n olá, pegue informções sobre a aluna')
print('nome:', nome)
print('idade:', idade)
print('altura:', altura)
print('hobbies:', hobbies)
print('Endereço:', endereço)
print('contato:', contato)

